version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - '5672:5672'
      - '15672:15672'

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres  # PostgreSQL username
      - POSTGRES_PASSWORD=postgres  # PostgreSQL password
    volumes:
      - ./pgdata:/var/ib/postgresql/data
    ports:
      - '5432:5432'


  neo4j:
    image: neo4j:latest
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=none

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'  # Your Node.js app port
    depends_on:
      - rabbitmq
      - postgres
      - neo4j